FRENCH_QUESTION_BANK = [
    {"id": "fr_tenses_1", "topic": "Tenses", "prompt": "Hier, je ___ au cinéma avec mes amis.", "options": {"A": "vais", "B": "suis allé(e)", "C": "irai", "D": "aller"}, "answer": "B"},
    {"id": "fr_tenses_2", "topic": "Tenses", "prompt": "Demain, nous ___ notre professeur.", "options": {"A": "avons rencontré", "B": "rencontrions", "C": "rencontrerons", "D": "rencontrons hier"}, "answer": "C"},
    {"id": "fr_tenses_3", "topic": "Tenses", "prompt": "Quand j'étais petit(e), je ___ souvent au parc.", "options": {"A": "vais", "B": "suis allé(e)", "C": "allais", "D": "irai"}, "answer": "C"},
    {"id": "fr_articles_1", "topic": "Articles", "prompt": "___ maison est très grande.", "options": {"A": "Le", "B": "La", "C": "Les", "D": "Un"}, "answer": "B"},
    {"id": "fr_articles_2", "topic": "Articles", "prompt": "J'ai acheté ___ livre intéressant.", "options": {"A": "une", "B": "la", "C": "un", "D": "des"}, "answer": "C"},
    {"id": "fr_articles_3", "topic": "Articles", "prompt": "Nous mangeons ___ pommes.", "options": {"A": "du", "B": "de la", "C": "des", "D": "le"}, "answer": "C"},
    {"id": "fr_prepositions_1", "topic": "Prepositions", "prompt": "Je vais ___ France cet été.", "options": {"A": "au", "B": "en", "C": "aux", "D": "à la"}, "answer": "B"},
    {"id": "fr_prepositions_2", "topic": "Prepositions", "prompt": "Elle habite ___ Paris.", "options": {"A": "en", "B": "au", "C": "à", "D": "aux"}, "answer": "C"},
    {"id": "fr_prepositions_3", "topic": "Prepositions", "prompt": "Le livre est ___ la table.", "options": {"A": "sur", "B": "de", "C": "chez", "D": "entre"}, "answer": "A"},
    {"id": "fr_agreement_1", "topic": "Agreement", "prompt": "Marie est ___ .", "options": {"A": "content", "B": "contente", "C": "contents", "D": "contentes"}, "answer": "B"},
    {"id": "fr_agreement_2", "topic": "Agreement", "prompt": "Les garçons sont ___.", "options": {"A": "intelligent", "B": "intelligente", "C": "intelligents", "D": "intelligentes"}, "answer": "C"},
    {"id": "fr_agreement_3", "topic": "Agreement", "prompt": "Les filles sont ___.", "options": {"A": "heureux", "B": "heureuse", "C": "heureuses", "D": "heureuxes"}, "answer": "C"},
    {"id": "fr_pronouns_1", "topic": "Pronouns", "prompt": "Marie parle à Paul. Elle ___ parle.", "options": {"A": "le", "B": "lui", "C": "les", "D": "leur"}, "answer": "B"},
    {"id": "fr_pronouns_2", "topic": "Pronouns", "prompt": "Je vois mes amis. Je ___ vois.", "options": {"A": "leur", "B": "lui", "C": "les", "D": "y"}, "answer": "C"},
    {"id": "fr_pronouns_3", "topic": "Pronouns", "prompt": "___ allons au collège tous les jours.", "options": {"A": "Ils", "B": "Nous", "C": "Elle", "D": "Lui"}, "answer": "B"},
    {"id": "fr_modals_1", "topic": "Modals", "prompt": "Je ___ parler français.", "options": {"A": "peux", "B": "dois", "C": "veux", "D": "toutes les réponses selon le contexte"}, "answer": "D"},
    {"id": "fr_modals_2", "topic": "Modals", "prompt": "Vous ___ faire vos devoirs avant de sortir.", "options": {"A": "devez", "B": "pouvez", "C": "voulez", "D": "allez"}, "answer": "A"},
    {"id": "fr_modals_3", "topic": "Modals", "prompt": "Elle ___ apprendre l'allemand.", "options": {"A": "veut", "B": "est", "C": "a", "D": "fait"}, "answer": "A"},
    {"id": "fr_conjunctions_1", "topic": "Conjunctions", "prompt": "Je reste à la maison ___ il pleut.", "options": {"A": "mais", "B": "parce qu'", "C": "ou", "D": "et"}, "answer": "B"},
    {"id": "fr_conjunctions_2", "topic": "Conjunctions", "prompt": "J'aime le thé ___ je n'aime pas le café.", "options": {"A": "parce que", "B": "mais", "C": "donc", "D": "quand"}, "answer": "B"},
    {"id": "fr_conjunctions_3", "topic": "Conjunctions", "prompt": "Il travaille beaucoup ___ il veut réussir.", "options": {"A": "parce qu'", "B": "mais", "C": "ou", "D": "si"}, "answer": "A"},
    {"id": "fr_conditionals_1", "topic": "Conditionals", "prompt": "Si j'avais le temps, je ___ plus.", "options": {"A": "voyage", "B": "voyagerai", "C": "voyagerais", "D": "voyageais"}, "answer": "C"},
    {"id": "fr_conditionals_2", "topic": "Conditionals", "prompt": "Si tu étudies, tu ___ l'examen.", "options": {"A": "réussiras", "B": "réussirais", "C": "réussissais", "D": "as réussi"}, "answer": "A"},
    {"id": "fr_conditionals_3", "topic": "Conditionals", "prompt": "Si j'étais riche, j'___ une grande maison.", "options": {"A": "achète", "B": "achèterais", "C": "achèterai", "D": "achetais"}, "answer": "B"},
    {"id": "fr_sentence_1", "topic": "Sentence Structure", "prompt": "Choisissez la phrase correcte.", "options": {"A": "Mange Marie une pomme.", "B": "Marie mange une pomme.", "C": "Une Marie mange pomme.", "D": "Mange une pomme Marie."}, "answer": "B"},
    {"id": "fr_sentence_2", "topic": "Sentence Structure", "prompt": "Choisissez la phrase correcte.", "options": {"A": "Je demain vais à Paris.", "B": "Demain je vais à Paris.", "C": "Je vais Paris à demain.", "D": "À Paris demain vais je."}, "answer": "B"},
    {"id": "fr_mixed_1", "topic": "Tenses - Mixed", "prompt": "Nous ___ déjà terminé nos devoirs.", "options": {"A": "avons", "B": "sommes", "C": "allons", "D": "étions"}, "answer": "A"},
    {"id": "fr_mixed_2", "topic": "Tenses - Mixed", "prompt": "Quand elle est arrivée, je ___ déjà parti.", "options": {"A": "suis", "B": "avais", "C": "ai", "D": "serai"}, "answer": "B"},
    {"id": "fr_mixed_3", "topic": "Tenses - Mixed", "prompt": "L'année prochaine, ils ___ leurs études.", "options": {"A": "terminent", "B": "terminaient", "C": "termineront", "D": "ont terminé"}, "answer": "C"},
]

GERMAN_QUESTION_BANK = [
    {"id": "de_tenses_1", "topic": "Tenses", "prompt": "Ich ___ gestern ins Kino gegangen.", "options": {"A": "bin", "B": "habe", "C": "werde", "D": "war"}, "answer": "A"},
    {"id": "de_tenses_2", "topic": "Tenses", "prompt": "Morgen ___ ich meine Freunde besuchen.", "options": {"A": "habe", "B": "bin", "C": "werde", "D": "war"}, "answer": "C"},
    {"id": "de_tenses_3", "topic": "Tenses", "prompt": "Als Kind ___ ich jeden Tag Fußball.", "options": {"A": "spiele", "B": "spielte", "C": "habe gespielt", "D": "werde spielen"}, "answer": "B"},
    {"id": "de_articles_1", "topic": "Articles", "prompt": "___ Tisch ist groß.", "options": {"A": "Die", "B": "Das", "C": "Der", "D": "Eine"}, "answer": "C"},
    {"id": "de_articles_2", "topic": "Articles", "prompt": "Ich habe ___ Buch gekauft.", "options": {"A": "ein", "B": "eine", "C": "einen", "D": "der"}, "answer": "A"},
    {"id": "de_articles_3", "topic": "Articles", "prompt": "___ Mädchen liest ein Buch.", "options": {"A": "Der", "B": "Die", "C": "Das", "D": "Den"}, "answer": "C"},
    {"id": "de_prepositions_1", "topic": "Prepositions", "prompt": "Ich fahre ___ Deutschland.", "options": {"A": "nach", "B": "zu", "C": "an", "D": "bei"}, "answer": "A"},
    {"id": "de_prepositions_2", "topic": "Prepositions", "prompt": "Das Buch liegt ___ dem Tisch.", "options": {"A": "auf", "B": "nach", "C": "zu", "D": "von"}, "answer": "A"},
    {"id": "de_prepositions_3", "topic": "Prepositions", "prompt": "Ich gehe ___ Schule.", "options": {"A": "in", "B": "zur", "C": "nach", "D": "aus"}, "answer": "B"},
    {"id": "de_agreement_1", "topic": "Agreement", "prompt": "Das ___ Mädchen ist sehr nett.", "options": {"A": "freundlich", "B": "freundliche", "C": "freundlicher", "D": "freundlichen"}, "answer": "B"},
    {"id": "de_agreement_2", "topic": "Agreement", "prompt": "Die ___ Kinder spielen im Garten.", "options": {"A": "klein", "B": "kleine", "C": "kleinen", "D": "kleiner"}, "answer": "C"},
    {"id": "de_agreement_3", "topic": "Agreement", "prompt": "Der ___ Mann arbeitet hier.", "options": {"A": "alt", "B": "alte", "C": "alten", "D": "altes"}, "answer": "B"},
    {"id": "de_pronouns_1", "topic": "Pronouns", "prompt": "Maria ist meine Freundin. ___ ist sehr nett.", "options": {"A": "Er", "B": "Sie", "C": "Es", "D": "Ihr"}, "answer": "B"},
    {"id": "de_pronouns_2", "topic": "Pronouns", "prompt": "Ich sehe meinen Bruder. Ich sehe ___.", "options": {"A": "er", "B": "ihm", "C": "ihn", "D": "sie"}, "answer": "C"},
    {"id": "de_pronouns_3", "topic": "Pronouns", "prompt": "Das Buch gehört mir. Es gehört ___.", "options": {"A": "ich", "B": "mich", "C": "mir", "D": "mein"}, "answer": "C"},
    {"id": "de_modals_1", "topic": "Modals", "prompt": "Ich ___ Deutsch sprechen.", "options": {"A": "kann", "B": "muss", "C": "soll", "D": "will"}, "answer": "A"},
    {"id": "de_modals_2", "topic": "Modals", "prompt": "Du ___ deine Hausaufgaben machen.", "options": {"A": "kannst", "B": "musst", "C": "willst", "D": "magst"}, "answer": "B"},
    {"id": "de_modals_3", "topic": "Modals", "prompt": "Wir ___ morgen ins Kino gehen.", "options": {"A": "wollen", "B": "sind", "C": "haben", "D": "werden gestern"}, "answer": "A"},
    {"id": "de_conjunctions_1", "topic": "Conjunctions", "prompt": "Ich bleibe zu Hause, ___ ich krank bin.", "options": {"A": "aber", "B": "weil", "C": "oder", "D": "und"}, "answer": "B"},
    {"id": "de_conjunctions_2", "topic": "Conjunctions", "prompt": "Ich lerne Deutsch, ___ ich in Deutschland studieren möchte.", "options": {"A": "weil", "B": "aber", "C": "oder", "D": "und"}, "answer": "A"},
    {"id": "de_conjunctions_3", "topic": "Conjunctions", "prompt": "Ich mag Kaffee, ___ ich mag keinen Tee.", "options": {"A": "weil", "B": "aber", "C": "wenn", "D": "dass"}, "answer": "B"},
    {"id": "de_conditionals_1", "topic": "Conditionals", "prompt": "Wenn ich Zeit hätte, ___ ich mehr reisen.", "options": {"A": "werde", "B": "würde", "C": "bin", "D": "habe"}, "answer": "B"},
    {"id": "de_conditionals_2", "topic": "Conditionals", "prompt": "Wenn du lernst, ___ du die Prüfung bestehen.", "options": {"A": "wirst", "B": "würdest", "C": "bist", "D": "hast"}, "answer": "A"},
    {"id": "de_conditionals_3", "topic": "Conditionals", "prompt": "Wenn ich reich wäre, ___ ich ein großes Haus kaufen.", "options": {"A": "werde", "B": "würde", "C": "kann", "D": "habe"}, "answer": "B"},
    {"id": "de_sentence_1", "topic": "Sentence Structure", "prompt": "Choose the correct sentence.", "options": {"A": "Ich heute gehe zur Schule.", "B": "Heute ich gehe zur Schule.", "C": "Ich gehe heute zur Schule.", "D": "Gehe ich heute Schule zur."}, "answer": "C"},
    {"id": "de_sentence_2", "topic": "Sentence Structure", "prompt": "Choose the correct sentence.", "options": {"A": "Ich Deutsch lerne.", "B": "Ich lerne Deutsch.", "C": "Deutsch ich lerne.", "D": "Lerne Deutsch ich."}, "answer": "B"},
    {"id": "de_sentence_3", "topic": "Sentence Structure", "prompt": "Choose the correct sentence.", "options": {"A": "Weil ich krank bin, bleibe ich zu Hause.", "B": "Weil ich bin krank, bleibe ich zu Hause.", "C": "Weil krank ich bin, bleibe ich zu Hause.", "D": "Weil ich krank, bin bleibe ich zu Hause."}, "answer": "A"},
    {"id": "de_mixed_1", "topic": "Tenses - Mixed", "prompt": "Ich ___ gestern einen Film gesehen.", "options": {"A": "habe", "B": "bin", "C": "werde", "D": "hatte"}, "answer": "A"},
    {"id": "de_mixed_2", "topic": "Tenses - Mixed", "prompt": "Wir ___ nächstes Jahr nach Berlin fahren.", "options": {"A": "sind", "B": "waren", "C": "werden", "D": "haben"}, "answer": "C"},
    {"id": "de_mixed_3", "topic": "Tenses - Mixed", "prompt": "Sie ___ schon gegessen, bevor ich kam.", "options": {"A": "hat", "B": "hatte", "C": "wird", "D": "ist"}, "answer": "B"},
]

LANGUAGE_QUESTION_BANKS = {
    "English": None,
    "French": FRENCH_QUESTION_BANK,
    "German": GERMAN_QUESTION_BANK,
}

LANGUAGE_WRITING_PROMPTS = {
    "French": [
        "Décrivez votre routine quotidienne.",
        "Parlez de votre loisir préféré.",
        "Décrivez une journée mémorable de votre vie.",
        "Parlez de votre expérience à l'université.",
        "Décrivez votre meilleur ami ou votre meilleure amie.",
        "Parlez d'un endroit que vous aimeriez visiter.",
        "Décrivez votre film ou livre préféré.",
        "Parlez de vos objectifs professionnels pour l'avenir.",
        "Expliquez comment la technologie influence votre vie quotidienne.",
        "Parlez d'une leçon importante que vous avez apprise.",
        "Décrivez votre fête ou festival préféré.",
        "Parlez de votre expérience en apprenant une nouvelle compétence.",
        "Décrivez votre week-end idéal.",
        "Expliquez pourquoi l'éducation est importante.",
        "Décrivez une personne qui vous inspire.",
    ],
    "German": [
        "Beschreiben Sie Ihren Tagesablauf.",
        "Schreiben Sie über Ihr Lieblingshobby.",
        "Beschreiben Sie einen unvergesslichen Tag in Ihrem Leben.",
        "Schreiben Sie über Ihre Erfahrungen an der Universität.",
        "Beschreiben Sie Ihren besten Freund oder Ihre beste Freundin.",
        "Schreiben Sie über einen Ort, den Sie gerne besuchen möchten.",
        "Beschreiben Sie Ihren Lieblingsfilm oder Ihr Lieblingsbuch.",
        "Schreiben Sie über Ihre beruflichen Ziele für die Zukunft.",
        "Schreiben Sie darüber, wie Technologie Ihren Alltag beeinflusst.",
        "Schreiben Sie über eine wichtige Lektion, die Sie gelernt haben.",
        "Beschreiben Sie Ihr Lieblingsfest.",
        "Schreiben Sie über Ihre Erfahrung beim Erlernen einer neuen Fähigkeit.",
        "Beschreiben Sie Ihr ideales Wochenende.",
        "Schreiben Sie über die Bedeutung von Bildung.",
        "Beschreiben Sie eine Person, die Sie inspiriert.",
    ],
}
